version: '3.7'

# command sample
# docker system prune -a -f && docker volume ls -qf dangling=true | xargs -r
# docker volume prune
# docker-compose -f ./docker/docker-pgt.yml up -d --build

services:

  postgresql:
    container_name: pgt
    build:
      context: ./pgt
      dockerfile: Dockerfile
    image: devenv/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      TZ: Asia/Tokyo
    logging:
      driver: json-file
      options:
        max-size: '5m'
        max-file: '1'
